# Generated by Django 5.2.6 on 2025-09-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeinfo_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='salary',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
