# Generated by Django 4.0 on 2025-09-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employeeinfo_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='role',
            field=models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('senior', 'Senior'), ('lead', 'Lead')], default='intern', max_length=20),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employee.employeeinfo')),
            ],
        ),
    ]
