# Generated by Django 4.0 on 2025-09-18 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeeinfo_role_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.CreateModel(
            name='TaksInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employee.employeeinfo')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tasks', to='employee.task')),
            ],
        ),
    ]
