# Generated by Django 4.0 on 2025-09-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_task_employee_taksinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
