# Generated by Django 4.0 on 2025-09-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_branch_employeeinfo_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='branch',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='branch',
            field=models.ManyToManyField(blank=True, null=True, related_name='branch', to='employee.Branch'),
        ),
    ]
