# Generated by Django 4.0 on 2025-09-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_employeeinfo_branch_employeeinfo_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='branch',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='employee.branch'),
        ),
    ]
