# Generated by Django 4.0 on 2025-09-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_remove_employeeinfo_branch_employeeinfo_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='can_view',
        ),
        migrations.CreateModel(
            name='BranchPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_employees', to='employee.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_permissions', to='employee.employeeinfo')),
            ],
        ),
    ]
