# Generated by Django 4.0 on 2025-09-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_employeeinfo_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchpermission',
            name='can_view',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
